language: php
sudo: false
addons:
  apt:
    packages:
      - ca-certificates
php:
  - '5.6'
  - '7.0'
before_install:
    - composer self-update

install:
  - composer install

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/coveralls -v
