language: php
sudo: true
php:
  - '5.6'
  - '7.0'
before_install:
  # We need this because Zenfolio uses a Comodo/AddTrust certificate not trusted by default.
  - echo -n | openssl s_client -connect api.zenfolio.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/coveralls -v
